---
title: "Fred API with  R"
author: Atang Mahlomaholo
date: now
---


## This will load necessary libraries

```{r}
#| echo: false
#| include: true
#| label: setup
#| warning: false


library(httr2)
library(rmarkdown)
```

## Source the script that has the Functions

```{r}
#| include: false
#| echo: false
#| warning: false
#| label: import-function

# get an api key from the fred website
json_file <- jsonlite::fromJSON("../secrets.json")

fred_api <- json_file$api_key


source("../scripts/fred-api.R")

```



## Get the `Fed Funds Rate` 


```{r}
#| include: true
#| warning: false
#| echo: false
#| label: use-function


fed_funds_df <- 
  get_fred_series(
    "DFF",
    "2000-01-01",
    "2024-11-01",
    "lin",
    fred_api)


TR_rate_dff <- 
  get_fred_series(
    "T10YFF",
    "2000-01-01",
    "2024-11-01",
    "lin",
    fred_api
  )

fed_funds_df

TR_rate_dff

```



## What if you want to download multiple series?


```{r}
#| label: multiple-series
#| include: true
#| warning: false
#| echo: false


more_series <- 
  get_more_series(
    c("DFF", "T10YFF", "DCOILBRENTEU"),
    "2000-01-01",
    "2024-11-01",
    "lin",
    fred_api)

more_series




# do data visuals using the data that has been downloaded 


fig1 <- more_series |> 
  ggplot2::ggplot(aes(x = date)) +
  geom_line(aes(y = DFF)) +
  geom_line(aes(y = T10YFF), 
            linetype = "dashed",
            color = "red")

fig1 + theme_bw()
```